--[III] JOIN : 테이블을 2개 이상 연결하여 검색

SELECT * FROM EMP WHERE ENAME = 'SCOTT';
SELECT * FROM DEPT; 

--CROSS JOIN(FROM절에 테이블 2개 이상)
SELECT * FROM EMP,DEPT WHERE ENAME = 'SCOTT';
--EQUI JOIN (공통 필드인 DEPTNO값이 일치되는 조건만 JOIN)
SELECT * FROM EMP,DEPT WHERE ENAME = 'SCOTT' AND EMP.DEPTNO=DEPT.DEPTNO;
SELECT * FROM EMP,DEPT WHERE EMP.DEPTNO = DEPT.DEPTNO;
--모든 사원의 이름,부서명, 부서번호
SELECT ENAME ,DNAME, E.DEPTNO FROM EMP E ,DEPT D 
    WHERE E.DEPTNO = D.DEPTNO;
SELECT E.*, DNAME,LOC
    FROM EMP E,DEPT D WHERE E.DEPTNO=D.DEPTNO;

--사번, 이름, 부서번호, 부서이름, 근무지 출력
SELECT EMPNO, ENAME, E.DEPTNO, DNAME,LOC
    FROM EMP E,DEPT D
    WHERE E.DEPTNO=D.DEPTNO;
--급여 2000 이상 직원만 이름, 업무, 급여, 부서명, 근무지 필드 출력
SELECT ENAME,JOB,SAL,DNAME,LOC FROM EMP E, DEPT D 
    WHERE E.DEPTNO=D.DEPTNO AND SAL>=2000;
--LOC이 CHICAGO인 사람의 이름, 업무, 부서명, 근무지 출력
SELECT ENAME,JOB, DNAME,LOC FROM EMP E, DEPT D 
    WHERE E.DEPTNO=D.DEPTNO AND LOC='CHICAGO';
--부서번호가 10 또는 20인 사원의 이름, 업무, 근무지 출력(급여순 정렬)
SELECT ENAME, JOB, LOC FROM EMP E, DEPT D
    WHERE E.DEPTNO=D.DEPTNO AND D.DEPTNO IN (10,20)
    ORDER BY SAL;
--이름, 급여, 상여(COMM), 연봉((급여+COMM)*12),부서명, 근무지
SELECT ENAME,SAL,COMM,(SAL+NVL(COMM,0))*12 "연봉", DNAME, LOC
    FROM EMP E, DEPT D
    WHERE E.DEPTNO=D.DEPTNO;
--이름, 급여, 상여(COMM), 연봉((급여+COMM)*12),부서명, 근무지
--JOB이 SALESMAN 또는 MANAGER인 사원만(연봉이 큰 순으로 정렬)
SELECT ENAME,SAL,COMM,(SAL+NVL(COMM,0))*12 "연봉", DNAME, LOC
    FROM EMP E, DEPT D
    WHERE E.DEPTNO=D.DEPTNO AND JOB IN('SALESMAN','MANAGER') --UPPER(JOB) 사용가능
    ORDER BY 연봉 DESC;
--COMM이 NULL이고 급여가 1200 이상인 사원의 이름, 급여 입사일, 부서번호, 부서명(부서명순, 급여큰순 정렬
SELECT ENAME, SAL,HIREDATE,E.DEPTNO,DNAME
    FROM EMP E, DEPT D
    WHERE E.DEPTNO=D.DEPTNO AND COMM IS NULL AND SAL>=1200
    ORDER BY DNAME, SAL DESC;

--EQUI JOIN 예제

-- TO_CHAR(날짜형, 'YY')
-- TO_CHAR(숫자형, 'YY')





